server:
  port: 8082
spring:
  application:
    name: RATING-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/RatingMicroservice
    username: root
    password: santosh1998$
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  config:
    import: optional:configserver:http://localhost:8085


#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka


# okta configuration...
okta:
  oauth2:
    issuer: https://dev-56654283.okta.com/oauth2/default
    audience: api://default

